split: camera_train
root_dir: ../data/nocs/
mask_pointcloud: True
normalize_pointcloud: True
scale_convention: half_max
camera_convention: opengl
# ShapeNetV2 object conventions
remap_y_axis: "y"
remap_x_axis: "-z"
