config:
    - "./discretized.yaml"
    - vae: "../vae_models/bottle.yaml"
    - generated_dataset: "./generated_dataset.yaml"

# Category-specific config
generated_dataset:
    z_min: 0.5
    z_max: 1.5
    extent_mean: 0.3
    extent_std: 0.08
