width: 640
height: 480
fov_deg: 90
pointcloud: True
normalize_pose: True
render_threshold: 0.004
z_min: 0.2
z_max: 1.5
extent_mean: 0.11
extent_std: 0.01
mask_noise: True
mask_noise_min: 0.1
mask_noise_max: 2.0
norm_noise: False
norm_noise_min: -0.1
norm_noise_max: 0.1
scale_to_unit_ball: False
gaussian_noise_probability: 0.5
