# Standalone config to use with real275_evaluation.py
config:
  config_dict:
    - ../../sdf_estimation/configs/default.yaml
    - category_configs:
        bottle: ../../sdf_estimation/models/bottle.yaml
        bowl: ../../sdf_estimation/models/bowl.yaml
        laptop: ../../sdf_estimation/models/laptop.yaml
        can: ../../sdf_estimation/models/can.yaml
        camera: ../../sdf_estimation/models/camera.yaml
        mug: ../../sdf_estimation/models/mug.yaml
    - prior: ./real275_priors.yaml

name: SDFEstPrior
wrapper_type: method_wrappers.SDFEstWrapper
config_dict:
  threshold: 0.005
  device: cuda:0
  num_points: 10000  # samples from mesh to generate pointcloud

  max_iterations: 50
  visualize_optimization: False

  camera:  # Placeholder, will be overwritten with dataset specific camera in wrapper
    width: 640
    height: 480
    fx: 591.0125
    fy: 590.16775
    cx: 322.525
    cy: 244.11084
    pixel_center: 0
