decoder:
  fc_layers:
  - {out: 20}
  - {out: 50}
  - {out: 8192}
  conv_layers:
  - {in_size: 8, in_channels: 16, out_channels: 16, kernel_size: 3, relu: true}
  - {in_size: 16, in_channels: 16, out_channels: 8, kernel_size: 3, relu: true}
  - {in_size: 32, in_channels: 8, out_channels: 4, kernel_size: 3, relu: true}
  - {in_size: 64, in_channels: 4, out_channels: 1, kernel_size: 1, relu: false}
latent_size: 8
tsdf: false
encoder:
  layer_infos:
  - type: torch.nn.Conv3d
    args: {in_channels: 1, out_channels: 4, kernel_size: 3, stride: 2}
  - type: torch.nn.ReLU
    args: {}
  - type: torch.nn.Conv3d
    args: {in_channels: 4, out_channels: 8, kernel_size: 3, stride: 2}
  - type: torch.nn.ReLU
    args: {}
  - type: torch.nn.Conv3d
    args: {in_channels: 8, out_channels: 16, kernel_size: 3, stride: 2}
  - type: torch.nn.ReLU
    args: {}
  - type: torch.nn.Flatten
    args: {}
iterations: 100000
batch_size: 16
l2_large_weight: 1.0
l2_small_weight: 10.0
l1_large_weight: 0.0
l1_small_weight: 0.0
pc_weight: 1.0
kld_weight: 3.0
learning_rate: 0.001
dataset_path: ./data/shapenet_processed/bottle_filtered/
model: ~/.sdfest/model_weights/bottle_vae.pt
model_url: https://github.com/roym899/sdfest/releases/download/v0.1.0/bottle_vae.pt
