# Standalone config to use with ROS
config:
  - real275.yaml
  - category_configs:
      mug: ./models/mug.yaml
      bottle: ./models/bottle.yaml
      bowl: ./models/bowl.yaml
      can: ./models/can.yaml
      camera: ./models/camera.yaml

threshold: 0.005
device: cuda
max_iterations: 50

visualize_optimization: False
log_folder: null
run_name: ''
result_selection_strategy: best_inlier_ratio

category_ids:
  mug: 0
  bottle: 1
  bowl: 2
  knife: 3
  fork: 4

# Map COCO categories to SDFEst categories
# Categories not included will be mapped to themselves.
coco_category_map:
  cup: mug
  frisbee: bowl  # some plates are sometimes classified as frisbees
  scissors: knife  # knife is sometimes classified as scissors
