# Standalone config to use with rendering_evaluation.py
# Ablation study on synthetic mug data
config:
  - ./rendering_evaluation.yaml
  - ../models/v2/mug.yaml
  - ablation_configs:
      discretized_1: ../models/v2/mug_discretized_1.yaml
      discretized_2: ../models/v2/mug_discretized_2.yaml
      quaternion: ../models/v2/mug_quaternion.yaml

num_views: [3,]
run_name: ablation_study
