# Mug category, no camera specification
vae:
  decoder:
    fc_layers:
    - {out: 20}
    - {out: 50}
    - {out: 8192}
    conv_layers:
    - {in_size: 8, in_channels: 16, out_channels: 16, kernel_size: 3, relu: true}
    - {in_size: 16, in_channels: 16, out_channels: 8, kernel_size: 3, relu: true}
    - {in_size: 32, in_channels: 8, out_channels: 4, kernel_size: 3, relu: true}
    - {in_size: 64, in_channels: 4, out_channels: 1, kernel_size: 1, relu: false}
  latent_size: 8
  tsdf: false
  encoder:
    layer_infos:
    - type: torch.nn.Conv3d
      args: {in_channels: 1, out_channels: 4, kernel_size: 3, stride: 2}
    - type: torch.nn.ReLU
      args: {}
    - type: torch.nn.Conv3d
      args: {in_channels: 4, out_channels: 8, kernel_size: 3, stride: 2}
    - type: torch.nn.ReLU
      args: {}
    - type: torch.nn.Conv3d
      args: {in_channels: 8, out_channels: 16, kernel_size: 3, stride: 2}
    - type: torch.nn.ReLU
      args: {}
    - type: torch.nn.Flatten
      args: {}
  iterations: 100000
  batch_size: 8
  l2_large_weight: 1.0
  l2_small_weight: 10.0
  l1_large_weight: 0.0
  l1_small_weight: 0.0
  pc_weight: 1.0
  kld_weight: 3.0
  learning_rate: 0.001
  dataset_path: ./data/shapenet_core_processed/mug_filtered
  device: cuda:0
  model: ../models/mug_vae.pt
init:
  generated_dataset:
    width: 640
    height: 480
    fov_deg: 90
    pointcloud: true
    normalize_pose: true
    render_threshold: 0.002
    z_min: 0.2
    z_max: 1.5
    extent_mean: 0.11
    extent_std: 0.01
  batch_size: 32
  iterations: 500000
  learning_rate: 1.0e-3
  position_weight: 1000
  scale_weight: 1000
  orientation_weight: 1
  backbone_type: VanillaPointNet
  backbone:
    in_size: 3    # dimension of input points
    mlp_out_sizes: [64, 64, 64, 128, 1024]
    batchnorm: true

  head_type: SDFPoseHead
  head:
    in_size: 1024   # number of input features
    mlp_out_sizes: [512, 256, 128]
    batchnorm: true
    orientation_repr: discretized
    grid_resolution: 1   # only for discretized orientation repr.
  device: cuda:0
  model: ../models/mug_init.pt
category: cup
