# Standalone config to use with real275_evaluation.py
config:
  - real275.yaml
  - category_configs:
      mug: mug.yaml
      bottle: bottle.yaml
      bowl: bowl.yaml


threshold: 0.005
device: cuda

init_view: first
num_views: [1, 2, 3]
camera_distance: 0.3
max_iterations: 30
visualize_optimization: False
visualize_meshes: False
visualize_points: False
visualize_input: False
visualize_results: False
iso_threshold: 0.02
log_folder: null
mode: seg
run_name: ''
