# Standalone config to use with real275_evaluation.py
config:
  - real275.yaml
  - category_configs:
      mug: mug.yaml
      bottle: bottle.yaml
      bowl: bowl.yaml

threshold: 0.005
device: cuda

max_iterations: 30
visualize_optimization: False
log_folder: null
run_name: ''
