config:
  - ./default.yaml

# See https://github.com/hughw19/NOCS_CVPR2019/blob/master/detect_eval.py for camera
# intrinsics (seems to be different from info.txt in the dataset folder).

camera:
  width: 640
  height: 480
  fx: 591.0125
  fy: 590.16775
  cx: 322.525
  cy: 244.11084
  pixel_center: 0
threshold: 0.003
device: cuda
dataset: "real275"
max_iterations: 150
