# Standalone config to use with ROS
config:
  - real275.yaml
  - category_configs:
      mug: ../models/v2/mug.yaml
      bottle: ../models/bottle.yaml
      bowl: ../models/bowl.yaml

threshold: 0.005
device: cuda
max_iterations: 150

visualize_optimization: False
log_folder: null
run_name: ''
