config:
    - "./discretized.yaml"
    - vae: "./vae_models/laptop.yaml"

# Category-specific dataset configs
category_str: laptop
datasets:
    generated_dataset:
        config_dict:
            z_min: 0.5
            z_max: 1.5
            extent_mean: 0.35
            extent_std: 0.1