config:
    - "./discretized.yaml"
    - vae: "./vae_models/bottle.yaml"

# Category-specific dataset configs
category_str: bottle
datasets:
    generated_dataset:
        config_dict:
            z_min: 0.5
            z_max: 1.5
            extent_mean: 0.3
            extent_std: 0.1
