config:
    - "./discretized.yaml"
    - vae: "./vae_models/camera.yaml"

# Category-specific dataset configs
category_str: camera
datasets:
    generated_dataset:
        config_dict:
            z_min: 0.3
            z_max: 1.5
            extent_mean: 0.2
            extent_std: 0.05