config:
    - "./discretized.yaml"
    - vae: "./vae_models/bowl.yaml"

# Category-specific config
category_str: bowl
datasets:
    generated_dataset:
        config_dict:
            z_min: 0.2
            z_max: 1.5
            extent_mean: 0.2
            extent_std: 0.05
            
