config:
    - "./discretized.yaml"
    - vae: "./vae_models/can.yaml"

# Category-specific dataset configs
category_str: can
datasets:
    generated_dataset:
        config_dict:
            z_min: 0.2
            z_max: 1.5
            extent_mean: 0.1
            extent_std: 0.02